from typing import Any, Dict, List, Tuple

from wms_client import WMSClient
from utils import csv_bytes_from_dicts_fixed


def _normalize_order_hdr(order: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": order.get("id"),
        "create_user": order.get("create_user"),
        "create_ts": order.get("create_ts"),
        "mod_user": order.get("mod_user"),
        "mod_ts": order.get("mod_ts"),
        "facility_id_id": order.get("facility_id", {}).get("id"),
        "facility_id_key": order.get("facility_id", {}).get("key"),
        "company_id_id": order.get("company_id", {}).get("id"),
        "company_id_key": order.get("company_id", {}).get("key"),
        "order_nbr": order.get("order_nbr"),
        "order_type_id_id": order.get("order_type_id", {}).get("id"),
        "order_type_id_key": order.get("order_type_id", {}).get("key"),
        "status_id": order.get("status_id"),
        "ord_date": order.get("ord_date"),
        "exp_date": order.get("exp_date"),
        "req_ship_date": order.get("req_ship_date"),
        "dest_facility_id": order.get("dest_facility_id"),
        "shipto_facility_id": order.get("shipto_facility_id"),
        "cust_name": order.get("cust_name"),
        "cust_addr": order.get("cust_addr"),
        "cust_addr2": order.get("cust_addr2"),
        "cust_addr3": order.get("cust_addr3"),
        "cust_city": order.get("cust_city"),
        "cust_state": order.get("cust_state"),
        "cust_zip": order.get("cust_zip"),
        "cust_country": order.get("cust_country"),
        "cust_phone_nbr": order.get("cust_phone_nbr"),
        "cust_email": order.get("cust_email"),
        "cust_nbr": order.get("cust_nbr"),
        "shipto_name": order.get("shipto_name"),
        "shipto_addr": order.get("shipto_addr"),
        "shipto_addr2": order.get("shipto_addr2"),
        "shipto_addr3": order.get("shipto_addr3"),
        "shipto_city": order.get("shipto_city"),
        "shipto_state": order.get("shipto_state"),
        "shipto_zip": order.get("shipto_zip"),
        "shipto_country": order.get("shipto_country"),
        "shipto_phone_nbr": order.get("shipto_phone_nbr"),
        "shipto_email": order.get("shipto_email"),
        "ref_nbr": order.get("ref_nbr"),
        "stage_location_id": order.get("stage_location_id"),
        "ship_via_ref_code": order.get("ship_via_ref_code"),
        "route_nbr": order.get("route_nbr"),
        "external_route": order.get("external_route"),
        "destination_company_id_id": order.get("destination_company_id", {}).get("id"),
        "destination_company_id_key": order.get("destination_company_id", {}).get("key"),
        "ship_via_id": order.get("ship_via_id"),
        "priority": order.get("priority"),
        "host_allocation_nbr": order.get("host_allocation_nbr"),
        "sales_order_nbr": order.get("sales_order_nbr"),
        "sales_channel": order.get("sales_channel"),
        "customer_po_nbr": order.get("customer_po_nbr"),
        "carrier_account_nbr": order.get("carrier_account_nbr"),
        "payment_method_id": order.get("payment_method_id"),
        "dest_dept_nbr": order.get("dest_dept_nbr"),
        "start_ship_date": order.get("start_ship_date"),
        "stop_ship_date": order.get("stop_ship_date"),
        "vas_group_code": order.get("vas_group_code"),
        "spl_instr": order.get("spl_instr"),
        "currency_code": order.get("currency_code"),
        "record_origin_code": order.get("record_origin_code"),
        "cust_contact": order.get("cust_contact"),
        "shipto_contact": order.get("shipto_contact"),
        "ob_lpn_type": order.get("ob_lpn_type"),
        "ob_lpn_type_id": order.get("ob_lpn_type_id"),
        "total_orig_ord_qty": order.get("total_orig_ord_qty"),
        "orig_sku_count": order.get("orig_sku_count"),
        "orig_sale_price": order.get("orig_sale_price"),
        "gift_msg": order.get("gift_msg"),
        "sched_ship_date": order.get("sched_ship_date"),
        "customer_po_type": order.get("customer_po_type"),
        "customer_vendor_code": order.get("customer_vendor_code"),
        "externally_planned_load_flg": order.get("externally_planned_load_flg"),
        "work_order_kit_id": order.get("work_order_kit_id"),
        "order_nbr_to_replace": order.get("order_nbr_to_replace"),
        "stop_ship_flg": order.get("stop_ship_flg"),
        "lpn_type_class": order.get("lpn_type_class"),
        "billto_carrier_account_nbr": order.get("billto_carrier_account_nbr"),
        "duties_carrier_account_nbr": order.get("duties_carrier_account_nbr"),
        "duties_payment_method_id": order.get("duties_payment_method_id"),
        "customs_broker_contact_id": order.get("customs_broker_contact_id"),
        "order_shipped_ts": order.get("order_shipped_ts"),
        "cust_field_1": order.get("cust_field_1"),
        "cust_field_2": order.get("cust_field_2"),
        "cust_field_3": order.get("cust_field_3"),
        "cust_field_4": order.get("cust_field_4"),
        "cust_field_5": order.get("cust_field_5"),
        "cust_date_1": order.get("cust_date_1"),
        "cust_date_2": order.get("cust_date_2"),
        "cust_date_3": order.get("cust_date_3"),
        "cust_date_4": order.get("cust_date_4"),
        "cust_date_5": order.get("cust_date_5"),
        "cust_number_1": order.get("cust_number_1"),
        "cust_number_2": order.get("cust_number_2"),
        "cust_number_3": order.get("cust_number_3"),
        "cust_number_4": order.get("cust_number_4"),
        "cust_number_5": order.get("cust_number_5"),
        "cust_decimal_1": order.get("cust_decimal_1"),
        "cust_decimal_2": order.get("cust_decimal_2"),
        "cust_decimal_3": order.get("cust_decimal_3"),
        "cust_decimal_4": order.get("cust_decimal_4"),
        "cust_decimal_5": order.get("cust_decimal_5"),
        "cust_short_text_1": order.get("cust_short_text_1"),
        "cust_short_text_2": order.get("cust_short_text_2"),
        "cust_short_text_3": order.get("cust_short_text_3"),
        "cust_short_text_4": order.get("cust_short_text_4"),
        "cust_short_text_5": order.get("cust_short_text_5"),
        "cust_short_text_6": order.get("cust_short_text_6"),
        "cust_short_text_7": order.get("cust_short_text_7"),
        "cust_short_text_8": order.get("cust_short_text_8"),
        "cust_short_text_9": order.get("cust_short_text_9"),
        "cust_short_text_10": order.get("cust_short_text_10"),
        "cust_short_text_11": order.get("cust_short_text_11"),
        "cust_short_text_12": order.get("cust_short_text_12"),
        "cust_long_text_1": order.get("cust_long_text_1"),
        "cust_long_text_2": order.get("cust_long_text_2"),
        "cust_long_text_3": order.get("cust_long_text_3"),
        "tms_parcel_shipment_nbr": order.get("tms_parcel_shipment_nbr"),
        "erp_source_hdr_ref": order.get("erp_source_hdr_ref"),
        "erp_source_system_ref": order.get("erp_source_system_ref"),
        "tms_order_hdr_ref": order.get("tms_order_hdr_ref"),
        "group_ref": order.get("group_ref"),
    }


def _fieldnames() -> List[str]:
    return [
        "id", "create_user", "create_ts", "mod_user", "mod_ts",
        "facility_id_id", "facility_id_key", "company_id_id", "company_id_key", "order_nbr",
        "order_type_id_id", "order_type_id_key", "status_id", "ord_date", "exp_date", "req_ship_date",
        "dest_facility_id", "shipto_facility_id", "cust_name", "cust_addr", "cust_addr2", "cust_addr3",
        "cust_city", "cust_state", "cust_zip", "cust_country", "cust_phone_nbr", "cust_email", "cust_nbr",
        "shipto_name", "shipto_addr", "shipto_addr2", "shipto_addr3", "shipto_city", "shipto_state",
        "shipto_zip", "shipto_country", "shipto_phone_nbr", "shipto_email", "ref_nbr", "stage_location_id",
        "ship_via_ref_code", "route_nbr", "external_route", "destination_company_id_id", "destination_company_id_key",
        "ship_via_id", "priority", "host_allocation_nbr", "sales_order_nbr", "sales_channel", "customer_po_nbr",
        "carrier_account_nbr", "payment_method_id", "dest_dept_nbr", "start_ship_date", "stop_ship_date",
        "vas_group_code", "spl_instr", "currency_code", "record_origin_code", "cust_contact", "shipto_contact",
        "ob_lpn_type", "ob_lpn_type_id", "total_orig_ord_qty", "orig_sku_count", "orig_sale_price", "gift_msg",
        "sched_ship_date", "customer_po_type", "customer_vendor_code", "externally_planned_load_flg",
        "work_order_kit_id", "order_nbr_to_replace", "stop_ship_flg", "lpn_type_class", "billto_carrier_account_nbr",
        "duties_carrier_account_nbr", "duties_payment_method_id", "customs_broker_contact_id", "order_shipped_ts",
        "cust_field_1", "cust_field_2", "cust_field_3", "cust_field_4", "cust_field_5",
        "cust_date_1", "cust_date_2", "cust_date_3", "cust_date_4", "cust_date_5",
        "cust_number_1", "cust_number_2", "cust_number_3", "cust_number_4", "cust_number_5",
        "cust_decimal_1", "cust_decimal_2", "cust_decimal_3", "cust_decimal_4", "cust_decimal_5",
        "cust_short_text_1", "cust_short_text_2", "cust_short_text_3", "cust_short_text_4", "cust_short_text_5",
        "cust_short_text_6", "cust_short_text_7", "cust_short_text_8", "cust_short_text_9", "cust_short_text_10",
        "cust_short_text_11", "cust_short_text_12", "cust_long_text_1", "cust_long_text_2", "cust_long_text_3",
        "tms_parcel_shipment_nbr", "erp_source_hdr_ref", "erp_source_system_ref", "tms_order_hdr_ref", "group_ref"
    ]


async def extract_order_hdr_csv_bytes(client: WMSClient) -> Tuple[str, bytes]:
    items: List[Dict[str, Any]] = await client.fetch_all("order_hdr")
    normalized = [_normalize_order_hdr(x) for x in items]
    csv_bytes = csv_bytes_from_dicts_fixed(normalized, _fieldnames())
    return "order_hdr.csv", csv_bytes
